### ISSUE TITLE
Not a real issue ! Disable peds

### ISSUE THREAD

**Issue by Alevhovic** [Evgenius33/Extended-LSPD#1]
Hello @Evgenius33,

thanks for your amazing work.

I have a question, we are on a RP server and we don't want the peds.

I can "blacklist" those peds with a plugins, but i don't have the model name.

Maybe we can disable the peds without any plugins ?

Thanks for your work / answer again.

**Comment by Alevhovic** [comment]
I try with "NPC_Control" to disabled those peds.

But other peds take place after them, again and again... 

Any idea ?

**Comment by evgenius33** [comment]
https://runtime.fivem.net/doc/natives/#_0xBE31FD6CE464AC59

**Comment by Alevhovic** [comment]
You are awesome, thank you dude !

Solved.
